import Link from "next/link";

const features = [
  {
    id: "fake-news",
    href: "/fake-news",
    icon: "🗞️",
    title: "Fake News Detector",
    description:
      "Paste any article, claim, or upload a news image and let our AI analyse the credibility of the content in seconds.",
    color: "from-indigo-500 to-purple-600",
    badge: "NLP Powered",
  },
  {
    id: "website-safety",
    href: "/website-safety",
    icon: "🔒",
    title: "Website Safety",
    description:
      "Check whether a domain is safe, malicious, or a phishing attempt before you click or enter credentials.",
    color: "from-emerald-500 to-teal-600",
    badge: "Real-time",
  },
  {
    id: "ai-content",
    href: "/ai-content",
    icon: "🤖",
    title: "AI Content Detector",
    description:
      "Find out if a piece of text or document was written by a human or generated by an AI model.",
    color: "from-rose-500 to-pink-600",
    badge: "ML Model",
  },
];

export const metadata = {
  title: "TruthGuard AI — Detect Misinformation & Stay Safe Online",
  description:
    "TruthGuard AI uses advanced machine learning to detect fake news, inspect website safety, and identify AI-generated content.",
};

export default function HomePage() {
  return (
    <div className="relative overflow-hidden">
      {/* Background blobs */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute -top-40 -left-40 h-[600px] w-[600px] rounded-full opacity-20 blur-3xl"
        style={{ background: "radial-gradient(circle, #6366f1, transparent)" }}
      />
      <div
        aria-hidden="true"
        className="pointer-events-none absolute top-60 right-0 h-[400px] w-[400px] rounded-full opacity-10 blur-3xl"
        style={{ background: "radial-gradient(circle, #8b5cf6, transparent)" }}
      />

      {/* Hero */}
      <section className="mx-auto max-w-4xl px-6 pt-24 pb-16 text-center">
        <span
          className="mb-4 inline-block rounded-full border px-4 py-1.5 text-xs font-semibold tracking-widest uppercase"
          style={{ borderColor: "var(--border)", color: "var(--accent)" }}
        >
          🛡️ AI-Powered Verification &amp; Security
        </span>

        <h1 className="mt-4 text-4xl sm:text-6xl font-extrabold leading-tight tracking-tight">
          Welcome to{" "}
          <span
            className="bg-clip-text text-transparent"
            style={{ backgroundImage: "linear-gradient(135deg, #6366f1, #a78bfa)" }}
          >
            TruthGuard AI
          </span>
        </h1>

        <p className="mx-auto mt-6 max-w-2xl text-base sm:text-lg leading-relaxed" style={{ color: "var(--text-muted)" }}>
          Your intelligent shield against misinformation. Detect fake news,
          verify website safety, and identify AI-generated content — all in one
          unified platform.
        </p>

        {/* Hero Actions */}
        <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
          <Link
            href="/fake-news"
            className="btn-glow px-6 py-3 rounded-xl text-sm font-bold text-white shadow-xl"
          >
            Start Analyzing Now →
          </Link>
          <Link
            href="/history"
            className="px-6 py-3 rounded-xl text-sm font-medium text-gray-300 bg-white/5 hover:bg-white/10 hover:text-white border border-white/10 transition-colors"
          >
            📜 View Scan History
          </Link>
        </div>
      </section>

      {/* Feature Cards */}
      <section id="features" className="mx-auto max-w-6xl px-6 pb-20">
        <h2 className="mb-10 text-center text-2xl sm:text-3xl font-bold">
          What can TruthGuard do?
        </h2>

        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((f) => (
            <Link
              key={f.id}
              id={`feature-card-${f.id}`}
              href={f.href}
              className="glass group flex flex-col gap-4 rounded-2xl p-6 transition-all duration-300 hover:-translate-y-1 hover:border-indigo-500/40 border border-white/5"
            >
              <div className="flex items-center justify-between">
                <span className="text-4xl">{f.icon}</span>
                <span
                  className={`rounded-full bg-gradient-to-r ${f.color} px-3 py-0.5 text-xs font-semibold text-white`}
                >
                  {f.badge}
                </span>
              </div>
              <h3 className="text-lg font-semibold">{f.title}</h3>
              <p className="text-sm leading-relaxed" style={{ color: "var(--text-muted)" }}>
                {f.description}
              </p>
              <span className="mt-auto text-sm font-semibold flex items-center gap-1 group-hover:gap-2 transition-all" style={{ color: "var(--accent)" }}>
                Try now →
              </span>
            </Link>
          ))}
        </div>
      </section>

      {/* Trust & Methodology Section */}
      <section className="mx-auto max-w-5xl px-6 pb-24">
        <div className="glass rounded-3xl p-8 sm:p-10 border border-white/10">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center md:text-left">
            <div>
              <span className="text-3xl mb-3 inline-block">🔬</span>
              <h4 className="text-base font-bold mb-1" style={{ color: "var(--text-primary)" }}>
                Multi-Factor Validation
              </h4>
              <p className="text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>
                Combines semantic credibility scoring, source consistency checks, and pattern-matching.
              </p>
            </div>
            <div>
              <span className="text-3xl mb-3 inline-block">⚡</span>
              <h4 className="text-base font-bold mb-1" style={{ color: "var(--text-primary)" }}>
                Real-Time Analysis
              </h4>
              <p className="text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>
                Instant URL safety assessments and rapid AI vs. human stylometric breakdown.
              </p>
            </div>
            <div>
              <span className="text-3xl mb-3 inline-block">🗂️</span>
              <h4 className="text-base font-bold mb-1" style={{ color: "var(--text-primary)" }}>
                Persistent Audit Trail
              </h4>
              <p className="text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>
                Automatic local/cloud logging of every scan for accountability and historical comparison.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
